name: native_id
description: Get unique identifier for android and iOS
version: 0.0.5
homepage: https://github.com/mixin27/flutter_native_id
issue_tracker: https://github.com/mixin27/flutter_native_id/issues
funding:
  - https://www.buymeacoffee.com/kyawzayartun98
screenshots:
  - description: "This screenshot shows the result for Android"
    path: example_android.png
  - description: "This screenshot shows the result for iOS"
    path: example_ios.png

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.mixin27.native_id
        pluginClass: NativeIdPlugin
      ios:
        pluginClass: NativeIdPlugin

topics:
  - imei
  - unique identifier
  - utility